
export const publications = {
  journalArticles: [
    {
      id: 'pub-18',
      type: 'journal',
      title: 'Advances in membrane distillation for wastewater treatment: Innovations, challenges, and sustainable opportunities',
      authors: ['R.V.Patel', 'A.Yadav', 'V.K.Shahi'], 
      journal: 'Science of the Total Environment',
      year: 2025,
      volume: '969',
      pages: '178749',
      citescore:'',
    impact_factor:'8.2',
    quartile:'Q1',
      image: '/images/research/journal/advances.jpeg',
      link: 'https://www.sciencedirect.com/science/article/abs/pii/S0048969725003833',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-17',
      type: 'journal',
      title: 'Chemical grafting of hydrophobic functional groups on polyvinylidene fluoride side chain for vacuum membrane distillation applications',
      authors: ['R.V.Patel', 'S.Chaubey', 'A.Yadav', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2024,
      volume: '12',
      pages: '112746',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical.jpeg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343724008765',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-16',
      type: 'journal',
      title: 'Carbon chain grafted polyvinylidene fluoride membranes for textile water remediation: Experimental and computational studies',
      authors: ['R.V.Patel', 'S.Chaubey', 'A.Yadav', 'B.G.Vyas', 'V.K.Shahi'],
      journal: 'Chemical Engineering Journal',
      year: 2025,
      volume: '509',
      pages: '160965',
     citescore:'20.6',
      impact_factor:'13.4',
    quartile:'Q1',
    image: '/images/research/journal/carbon.png',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1385894725017863',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-15',
      type: 'journal',
      title: 'Adsorptive removal of norfloxacin from water using polyvinylidene fluoride-boron nitride nanosheets mixed matrix membrane: Insights from experiments and molecular dynamics simulation',
      authors: ['P.Awasthi', 'A.Yadav', 'N.Sinha'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2025,
      volume: '13',
      pages: '115783',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical.jpeg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343725004786',
      publisher: 'Elsevier',
      featured: false
    },

{
  id: 'pub-33',
  type: 'journal',
  title: 'Simultaneous adsorption of methylene blue and arsenic on graphene, boron nitride and boron carbon nitride nanosheets: Insights from molecular simulations',
  authors: ['A. Yadav', 'S.S. Dindonkar', 'S. Babu', 'N. Sinha'],
  journal: 'Journal of Water Process Engineering',
  year: 2022,
  volume: '46',
  pages: '102653',
  citescore: '10.3',
  impact_factor: '7.3',
  quartile: 'Q1',
  image: '/images/research/journal/jwpe.jpg',
  link: 'https://doi.org/10.1016/j.jwpe.2022.102653',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-34',
  type: 'journal',
  title: 'Effect of TiC and graphite reinforcement on hardness and wear behaviour of copper alloy B-RG10 composites fabricated through powder metallurgy',
  authors: ['F. Hasan', 'R. Jaiswal', 'A. Kumar', 'A. Yadav'],
  journal: 'JMST Advances',
  year: 2022,
  volume: '4',
  pages: '1-11',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/jmst_advances.jpg',
  link: 'https://doi.org/10.1007/s42791-022-00043-5',
  publisher: 'Springer',
  featured: false
},
{
  id: 'pub-35',
  type: 'journal',
  title: 'Zinc Ferrite Thin Film Deposited Directly on Interdigitated Electrode via CMOS Compatible Microwave Route for Highly Stable H2S Detection',
  authors: ['R.K. Jha', 'A. Nanda', 'R. Sai', 'K. Kishore', 'A. Yadav', 'R.D.R. Kahmei', 'Navakanta Bhat'],
  journal: 'IEEE Sensors Journal',
  year: 2022,
  volume: '22(9)',
  pages: '8402-8409',
  citescore: '8.9',
  impact_factor: '4.3',
  quartile: 'Q1',
  image: '/images/research/journal/ieee_sensors.jpg',
  link: 'https://doi.org/10.1109/JSEN.2022.3149980',
  publisher: 'IEEE',
  featured: false
},
{
  id: 'pub-36',
  type: 'journal',
  title: 'Scalable Approach to Develop High Performance Chemiresistive Nitric Oxide Sensor',
  authors: ['R.K. Jha', 'A. Nanda', 'P. Awasthi', 'N. Arya', 'V. Balakrishnan', 'A. Yadav', 'N. Bhat'],
  journal: 'IEEE Transactions on Nanotechnology',
  year: 2022,
  volume: '21',
  pages: '177-184',
  citescore: '6.2',
  impact_factor: '2.8',
  quartile: 'Q2',
  image: '/images/research/journal/ieee_nanotech.jpg',
  link: 'https://doi.org/10.1109/TNANO.2022.3149710',
  publisher: 'IEEE',
  featured: false
},
{
  id: 'pub-37',
  type: 'journal',
  title: 'Sustainable adsorptive removal of antibiotics from aqueous streams using Fe3O4-functionalized MIL101(Fe) chitosan composite beads',
  authors: ['P. Yadav', 'A. Yadav', 'P.K. Labhasetwar'],
  journal: 'Environmental Science and Pollution Research',
  year: 2022,
  volume: '29(4)',
  pages: '',
  citescore: '6.6',
  impact_factor: '5.8',
  quartile: 'Q1',
  image: '/images/research/journal/espr.jpg',
  link: 'https://doi.org/10.1007/s11356-021-18385-3',
  publisher: 'Springer',
  featured: false
},
{
  id: 'pub-38',
  type: 'journal',
  title: 'Synchronous Removal of Arsenic and Fluoride from Aqueous solution: A Facile approach to Fabricate Novel Functional Metallopolymer Microspheres',
  authors: ['A.R. Gupta', 'V.C. Joshi', 'A. Yadav', 'S. Sharma'],
  journal: 'ACS Omega',
  year: 2022,
  volume: '7(6)',
  pages: '4879–4891',
  citescore: '4.2',
  impact_factor: '3.4',
  quartile: 'Q2',
  image: '/images/research/journal/acs_omega.jpg',
  link: 'https://doi.org/10.1021/acsomega.1c05456',
  publisher: 'ACS Publications',
  featured: false
},
{
  id: 'pub-39',
  type: 'journal',
  title: 'Effect of TiC Reinforcement on Mechanical and Wear Properties of AZ91 Matrix Composites',
  authors: ['A. Kumar', 'S. Kumar', 'N.K. Mukhopadhyaya', 'A. Yadav', 'D.K. Sinha'],
  journal: 'International Journal of Metalcasting',
  year: 2022,
  volume: '16',
  pages: '2128-2143',
  citescore: '4.4',
  impact_factor: '2.0',
  quartile: 'Q2',
  image: '/images/research/journal/metalcasting.jpg',
  link: 'https://doi.org/10.1007/s40962-021-00747-9',
  publisher: 'Springer',
  featured: false
},
{
  id: 'pub-40',
  type: 'journal',
  title: 'Adsorption behaviour of hexagonal boron nitride towards cationic, anionic and neutral dyes: Insights from theoretical studies',
  authors: ['A. Yadav', 'S.S. Dindonkar'],
  journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
  year: 2022,
  volume: '641',
  pages: '128509',
  citescore: '9.1',
  impact_factor: '6.0',
  quartile: 'Q1',
  image: '/images/research/journal/colloids_surfaces_a.jpg',
  link: 'https://doi.org/10.1016/j.colsurfa.2022.128509',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-41',
  type: 'journal',
  title: 'Projections for profitability assessment parameters under short-term, medium-term and long-term evaluation for three farming techniques of Kappaphycus alvarezii along Eastern coast of India',
  authors: ['V.A. Mantri', 'R. Dineshkumar', 'A. Yadav', 'K. Eswaran', 'M. Shanmuagm', 'T. Gajaria'],
  journal: 'Aquaculture',
  year: 2022,
  volume: '551',
  pages: '737912',
  citescore: '8.5',
  impact_factor: '5.2',
  quartile: 'Q1',
  image: '/images/research/journal/aquaculture.jpg',
  link: 'https://doi.org/10.1016/j.aquaculture.2022.737912',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-42',
  type: 'journal',
  title: 'Adsorption behaviour of boron nitride nanosheets towards positive, negative and neutral antibiotics: Insights from first principle studies',
  authors: ['A. Yadav', 'S.S. Dindonkar', 'S. Babu'],
  journal: 'Journal of Water Process Engineering',
  year: 2022,
  volume: '46',
  pages: '102555',
  citescore: '10.3',
  impact_factor: '7.3',
  quartile: 'Q1',
  image: '/images/research/journal/jwpe.jpg',
  link: 'https://doi.org/10.1016/j.jwpe.2021.102555',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-43',
  type: 'journal',
  title: 'Boron nitride nanosheets incorporated polyvinylidene fluoride mixed matrix membranes for removal of methylene blue from aqueous stream',
  authors: ['R.S. Bangari', 'A. Yadav', 'J. Bharadwaj', 'N. Sinha'],
  journal: 'Journal of Environmental Chemical Engineering',
  year: 2022,
  volume: '10(1)',
  pages: '107052',
  citescore: '9.3',
  impact_factor: '7.8',
  quartile: 'Q1',
  image: '/images/research/journal/jece.jpg',
  link: 'https://doi.org/10.1016/j.jece.2021.107052',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-44',
  type: 'journal',
  title: 'Photocatalytic MIL101(Fe)/ZnO chitosan composites for adsorptive removal of tetracycline antibiotics from the aqueous stream',
  authors: ['R.V. Patel', 'A. Yadav'],
  journal: 'Journal of Molecular Structure',
  year: 2022,
  volume: '1252',
  pages: '132128',
  citescore: '6.2',
  impact_factor: '3.4',
  quartile: 'Q2',
  image: '/images/research/journal/mol_structure.jpg',
  link: 'https://doi.org/10.1016/j.molstruc.2021.132128',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-45',
  type: 'journal',
  title: 'Experimental and Theoretical Analysis of Simultaneous Removal of Methylene Blue and Tetracycline using Boron Nitride Nanosheets as Adsorbents',
  authors: ['R.S. Bangari', 'A. Yadav', 'P. Awasthi', 'N. Sinha'],
  journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
  year: 2022,
  volume: '634',
  pages: '127858',
  citescore: '9.1',
  impact_factor: '6.0',
  quartile: 'Q1',
  image: '/images/research/journal/colloids_surfaces_a.jpg',
  link: 'https://doi.org/10.1016/j.colsurfa.2021.127943',
  publisher: 'Elsevier',
  featured: false
},
    
    {
      id: 'pub-14',
      type: 'journal',
      title: 'Side-chain grafted functional groups poly(vinylidene fluoride-hexafluoropropylene) anti-fouling fluorinated polymer membrane with tuneable hydrophobicity for distillation',
      authors: ['A.Yadav', 'K.Singh', 'V.K.Shahi'],
      journal: 'Desalination',
      year: 2022,
      volume: '525',
      pages: '115501',
      citescore:'14.3',
      impact_factor:'8.4',
    quartile:'Q1',
    image: '/images/research/journal/desalinations.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0011916421005725',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-13',
      type: 'journal',
      title: 'Investigations on the effect of spacer in direct contact and air gap membrane distillation using computational fluid dynamics',
      authors: ['A.Yadav', 'C.P.Singh', 'R.V.Patel', 'A.Kumar', 'P.K.Labhasetwar'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '654',
      pages: '130111',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_654.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722018660',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-12',
      type: 'journal',
      title: 'Hexagonal boron nitride nanosheets incorporated photocatalytic polyvinylidene fluoride mixed matrix membranes for textile wastewater treatment via vacuum-assisted distillation',
      authors: ['A.Yadav', 'R.V.Patel', 'P.Awasthi', 'N.Sinha', 'P.K.Labhasetwar'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '653',
      pages: '129955',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_653.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722017101',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-11',
      type: 'journal',
      title: 'Recovery of CaSO4 and NaCl from sub-soil brine using CNT@MOF5 incorporated poly(vinylidene fluoride-hexafluoropropylene) membranes via vacuum-assisted distillation',
      authors: ['A.Yadav', 'R.V.Patel', 'B.G.Vyas', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '645',
      pages: '128918',
    citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_645.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722006732',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-10',
      type: 'journal',
      title: 'Experimental study and numerical optimization for removal of methyl orange using polytetrafluoroethylene membranes in vacuum membrane distillation process',
      authors: ['A.Yadav', 'R.V.Patel', 'C.P.Singh', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '635',
      pages: '128070',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_635.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775721019397',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-09',
      type: 'journal',
      title: 'Structural tailoring of ceria nanoparticles for fabricating fouling resistant nanocomposite membranes with high flux distillation',
      authors: ['A.Yadav', 'J.R.Mandal', 'A.B.Panda', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '633',
      pages: '127858',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_633.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775721017271',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-08',
      type: 'journal',
      title: 'Computational fluid dynamics based numerical simulations of heat transfer, fluid flow and mass transfer in vacuum membrane distillation process',
      authors: ['A.Yadav', 'C.P.Singh', 'R.V.Patel', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Water Supply',
      year: 2022,
      volume: '22',
      pages: '6262-6280',
      citescore:'N/A',
      impact_factor:'1.9',
    quartile:'Q2',
    image: '/images/research/journal/computational.jpg',
    link: 'https://iwaponline.com/ws/article/22/7/6262/88697/Computational-fluid-dynamics-based-numerical',
      publisher: 'International Water Association',
      featured: false
    },
    {
      id: 'pub-07',
      type: 'journal',
      title: 'Membrane distillation crystallization technology for zero liquid discharge and resource recovery: Opportunities, challenges and futuristic perspectives',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Science of The Total Environment',
      year: 2022,
      volume: '806',
      pages: '150692',
      citescore:'16.4',
      impact_factor:'8.2',
    quartile:'Q1',
    image: '/images/research/journal/membrane_806.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0048969721057703',
      publisher: 'Elsevier',
      featured: true
    },

{
  id: 'pub-99',
  type: 'journal',
  title: 'Experimental and numerical study on physico-mechanical properties and Taguchi\'s designed abrasive wear behavior of hemp/nettle-polyester hybrid composite',
  authors: ['S. Kumar', 'L. Prasad', 'V.K. Patel', 'A. Kumain', 'A. Yadav'],
  journal: 'Polymer Composites',
  year: 2021,
  volume: '42(12)',
  pages: '6912-6927',
  citescore: '',
  impact_factor: '2.6',
  quartile: 'Q2',
  image: '/images/research/journal/polymer_composites.jpg',
  link: 'https://doi.org/10.1002/pc.26350',
  publisher: 'Wiley',
  featured: false
},
{
  id: 'pub-100',
  type: 'journal',
  title: 'Adsorption of cupric, cadmium and cobalt ions from the aqueous stream using the composite of iron (II, III) oxide and zeolitic imidazole framework-8',
  authors: ['P. Kuwer', 'A. Yadav', 'P.K. Labhasetwar'],
  journal: 'Water Science and Technology',
  year: 2021,
  volume: '84(9)',
  pages: '2288-2303',
  citescore: '',
  impact_factor: '1.9',
  quartile: 'Q3',
  image: '/images/research/journal/water_science_technology.jpg',
  link: 'https://doi.org/10.2166/wst.2021.452',
  publisher: 'IWA Publishing',
  featured: false
},
{
  id: 'pub-101',
  type: 'journal',
  title: 'Highly sensitive, ambient temperature CO sensor using tin oxide based composites',
  authors: ['V. Kishnani', 'G. Verma', 'P.K. Pippara', 'A. Yadav', 'P.S. Chauhan', 'A. Gupta'],
  journal: 'Sensors and Actuators A: Physical',
  year: 2021,
  volume: '332',
  pages: '113111',
  citescore: '',
  impact_factor: '4.3',
  quartile: 'Q1',
  image: '/images/research/journal/sensors_actuators_a.jpg',
  link: 'https://doi.org/10.1016/j.sna.2021.113111',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-102',
  type: 'journal',
  title: 'Palladium-Functionalized Graphene for Hydrogen Sensing Performance: Theoretical Studies',
  authors: ['V. Kishnani', 'A. Yadav', 'A. Gupta', 'K. Mondal'],
  journal: 'Energies',
  year: 2021,
  volume: '14(18)',
  pages: '5738',
  citescore: '5.0',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/energies.jpg',
  link: 'https://doi.org/10.3390/en14185738',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-103',
  type: 'journal',
  title: 'Organic polymers for drinking water purification',
  authors: ['A. Yadav', 'N. Sinha'],
  journal: 'Encyclopedia',
  year: 2022,
  volume: '2',
  pages: '997-1003',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/encyclopedia.jpg',
  link: 'https://doi.org/10.1016/B978-0-12-820352-1.00140-1',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-104',
  type: 'journal',
  title: 'Experimental Investigation and Mathematical Modelling of Heat Transfer Coefficient in Double Slope Solar Still',
  authors: ['R.V. Patel', 'A. Yadav', 'J. Winczek'],
  journal: 'Strojniški Vestnik – Journal of Mechanical Engineering',
  year: 2021,
  volume: '67(7-8)',
  pages: '369-379',
  citescore: '',
  impact_factor: '1.5',
  quartile: 'Q3',
  image: '/images/research/journal/strojnicki_vestnik.jpg',
  link: 'https://doi.org/10.5545/sv-jme.2021.7156',
  publisher: 'Slovenian Society of Mechanical Engineers',
  featured: false
},
{
  id: 'pub-105',
  type: 'journal',
  title: 'Gas sensors applications for water quality monitoring and maintenance',
  authors: ['A. Yadav', 'P.D. Indurkar'],
  journal: 'Water Conservation Science and Engineering',
  year: 2021,
  volume: '6',
  pages: '175-190',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/water_conservation.jpg',
  link: 'https://doi.org/10.1007/s41101-021-00108-x',
  publisher: 'Springer',
  featured: false
},

    
    {
      id: 'pub-06',
      type: 'journal',
      title: 'Membrane distillation crystallization for simultaneous recovery of water and salt from tannery industry wastewater using TiO2 modified poly(vinylidene fluoride-co-hexafluoropropylene) nanocomposite membranes',
      authors: ['A.Yadav', 'K.Singh', 'A.B.Panda', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Water Process Engineering',
      year: 2021,
      volume: '44',
      pages: '102393',
      citescore:'9.6',
      impact_factor:'6.3',
    quartile:'Q1',
    image: '/images/research/journal/membrane_44.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2214714421004803',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-05',
      type: 'journal',
      title: 'Novel MIL101(Fe) impregnated poly(vinylidene fluoride-co-hexafluoropropylene) mixed matrix membranes for dye removal from textile industry wastewater',
      authors: ['A.Yadav', 'R.V.Patel', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Water Process Engineering',
      year: 2021,
      volume: '43',
      pages: '102317',
      citescore:'9.6',
      impact_factor:'6.3',
    quartile:'Q1',
    image: '/images/research/journal/water_43.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2214714421004049',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-04',
      type: 'journal',
      title: 'CNT functionalized ZIF-8 impregnated poly(vinylidene fluoride-co-hexafluoropropylene) mixed matrix membranes for antibiotics removal from pharmaceutical industry wastewater by vacuum membrane distillation',
      authors: ['A.Yadav', 'P.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '106560',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721015372',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-03',
      type: 'journal',
      title: 'Photocatalytic TiO2 incorporated PVDF-co-HFP UV-cleaning mixed matrix membranes for effective removal of dyes from synthetic wastewater system via membrane distillation',
      authors: ['A.Yadav', 'P.Sharma', 'A.B.Panda', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '105904',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721008812',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-02',
      type: 'journal',
      title: 'Membrane distillation using low-grade energy for desalination: A review',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '105818',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721007958',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-01',
      type: 'journal',
      title: 'Fabrication and optimization of tunable pore size poly(ethylene glycol) modified poly(vinylidene-co-hexafluoropropylene) membranes in vacuum membrane distillation for desalination',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Separation and Purification Technology',
      year: 2021,
      volume: '271',
      pages: '118840',
      citescore:'15.1',
      impact_factor:'8.2',
    quartile:'Q1',
    image: '/images/research/journal/seperation.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1383586621005529',
      publisher: 'Elsevier',
      featured: false
    },

{
  id: 'pub-87',
  type: 'journal',
  title: 'Mechanical and Microstructural Characterization of Friction Stir Welded SiC and B4C Reinforced AA6061 Aluminum Alloy AA6061 Metal Matrix Composites',
  authors: ['K.S.A. Ali', 'V. Mohanavel', 'S.A. Vendan', 'M. Ravichandran', 'A. Yadav', 'M. Gucwa', 'J. Winczek'],
  journal: 'Materials',
  year: 2021,
  volume: '14',
  pages: '3110',
  citescore: '6.4',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/materials.jpg',
  link: 'https://doi.org/10.3390/ma14113110',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-88',
  type: 'journal',
  title: 'Room Temperature Hydrogen Sensing with Polyaniline/SnO₂/Pd Nanocomposites',
  authors: ['R.K. Pippara', 'P.S. Chauhan', 'A. Yadav', 'V. Kishnani', 'A. Gupta'],
  journal: 'Micro and Nano Engineering',
  year: 2021,
  volume: '12',
  pages: '100086',
  citescore: '',
  impact_factor: '3.35',
  quartile: 'Q2',
  image: '/images/research/journal/micro_nano_engineering.jpg',
  link: 'https://doi.org/10.1016/j.mne.2021.100086',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-89',
  type: 'journal',
  title: 'In Situ Formation of ZrB₂ and Its Influence on Wear and Mechanical Properties of ADC12 Alloy Mixed Matrix Composites',
  authors: ['L. Prasad', 'N. Kumar', 'A. Yadav', 'A. Kumar', 'V. Kumar', 'J. Winczek'],
  journal: 'Materials',
  year: 2021,
  volume: '14',
  pages: '2141',
  citescore: '6.4',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/materials.jpg',
  link: 'https://doi.org/10.3390/ma14092141',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-90',
  type: 'journal',
  title: 'Physical and Mechanical Properties of Natural Leaf Fiber-Reinforced Epoxy Polyester Composites',
  authors: ['S. Kumar', 'L. Prasad', 'V.K. Patel', 'V. Kumar', 'A. Kumar', 'A. Yadav', 'J. Winczek'],
  journal: 'Polymers',
  year: 2021,
  volume: '13',
  pages: '1369',
  citescore: '',
  impact_factor: '4.9',
  quartile: 'Q1',
  image: '/images/research/journal/polymers.jpg',
  link: 'https://doi.org/10.3390/polym13091369',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-91',
  type: 'journal',
  title: '“Proof of concept” of how tube-net diameter affects growth and agar content in industrially important farmed red seaweed Gracilaria dura',
  authors: ['Y. Shah', 'A. Yadav', 'A.K. Madhava', 'M. Kavale', 'K. Prasad', 'V. Mantri'],
  journal: 'Journal of Applied Phycology',
  year: 2021,
  volume: '33',
  pages: '2349-2358',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/j_applied_phycology.jpg',
  link: 'https://doi.org/10.1007/s10811-021-02443-x',
  publisher: 'Springer',
  featured: false
},
{
  id: 'pub-92',
  type: 'journal',
  title: 'Zirconium-silver nano organo-bimetallic network for scavenging hazardous ions from water and its antibacterial potentiality: An environment-friendly approach',
  authors: ['A.R. Gupta', 'B. Ranawat', 'A. Singh', 'A. Yadav', 'S. Sharma'],
  journal: 'Journal of Environmental Chemical Engineering',
  year: 2021,
  volume: '9',
  pages: '105356',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/reresearch/journal/j_env_chem_eng.jpg',
  link: 'https://doi.org/10.1016/j.jece.2021.105356',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-93',
  type: 'journal',
  title: 'Scavenging fluoride from the aqueous system with porous organometallic three-dimensional architecture: An emerging adsorbent',
  authors: ['A.R. Gupta', 'A. Yadav', 'S. Sharma'],
  journal: 'Environmental Science and Pollution Research',
  year: 2021,
  volume: '28',
  pages: '19166-19178',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/env_sci_pollution.jpg',
  link: 'https://doi.org/10.1007/s11356-020-11916-4',
  publisher: 'Springer',
  featured: false
},
{
  id: 'pub-94',
  type: 'journal',
  title: 'Effect of Variation of SiC Reinforcement on Wear Behaviour of AZ91 Alloy Composites',
  authors: ['A. Kumar', 'S. Kumar', 'N.K. Mukhopadhyaya', 'A. Yadav', 'V. Kumar', 'J. Winczek'],
  journal: 'Materials',
  year: 2021,
  volume: '14',
  pages: '990',
  citescore: '6.4',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/materials.jpg',
  link: 'https://doi.org/10.3390/ma14040990',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-95',
  type: 'journal',
  title: 'Initial comparison between monoline and tube net method of farming in red agarophyte Gracilaria dura: Evidence from hydrodynamic CFD simulations',
  authors: ['M. Kavale', 'A. Yadav', 'V. A. Mantri'],
  journal: 'Aquaculture',
  year: 2021,
  volume: '536',
  pages: '736485',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/aquaculture.jpg',
  link: 'https://doi.org/10.1016/j.aquaculture.2021.736485',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-96',
  type: 'journal',
  title: 'Experimental and theoretical investigations of methyl orange adsorption using boron nitride nanosheets',
  authors: ['R.S. Bangari', 'A. Yadav', 'N. Sinha'],
  journal: 'Soft Matter',
  year: 2021,
  volume: '17',
  pages: '2640-2651',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/soft_matter.jpg',
  link: 'https://doi.org/10.1039/D1SM00048A',
  publisher: 'Royal Society of Chemistry (RSC)',
  featured: false
},
{
  id: 'pub-97',
  type: 'journal',
  title: 'High aspect ZnO nanorod growth over electrodeposited tubes for photocatalytic degradation of EtBr dye',
  authors: ['H.J. Biswal', 'A. Yadav', 'P.R. Vundavillia', 'A. Gupta'],
  journal: 'RSC Advances',
  year: 2021,
  volume: '11',
  pages: '1623-1634',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/rsc_advances.jpg',
  link: 'https://doi.org/10.1039/d0ra08124h',
  publisher: 'Royal Society of Chemistry',
  featured: false
},
{
  id: 'pub-98',
  type: 'journal',
  title: 'Reduced graphene oxide based hybrid functionalized films for hydrogen detection: Theoretical and experimental studies',
  authors: ['P. Pal', 'A. Yadav', 'P.S. Chauhan', 'P.K. Parida', 'A. Gupta'],
  journal: 'Sensors International',
  year: 2021,
  volume: '2',
  pages: '10072',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/sensors_international.jpg',
  link: 'https://doi.org/10.1016/j.sintl.2020.100072',
  publisher: 'Elsevier',
  featured: false
},

 {
  id: 'pub-112',
  type: 'journal',
  title: 'Effect of SiC Reinforcement and Its Variation on the Mechanical Characteristics of AZ91 Composites',
  authors: ['A. Kumar', 'S. Kumar', 'N.K. Mukhopadhyaya', 'A. Yadav', 'J. Winczek'],
  journal: 'Materials',
  year: 2020,
  volume: '13',
  pages: '4913',
  citescore: '6.4',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/materials.jpg',
  link: 'https://doi.org/10.3390/ma13214913',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-113',
  type: 'journal',
  title: 'Physical and Mechanical Behaviour of Sugarcane Bagasse Fibre-Reinforced Epoxy Bio-Composites',
  authors: ['L. Prasad', 'S. Kumar', 'R.V. Patel', 'A. Yadav', 'V. Kumar', 'J. Winczek'],
  journal: 'Materials',
  year: 2020,
  volume: '13',
  pages: '5387',
  citescore: '6.4',
  impact_factor: '3.2',
  quartile: 'Q2',
  image: '/images/research/journal/materials.jpg',
  link: 'https://doi.org/10.3390/ma13235387',
  publisher: 'MDPI',
  featured: false
},
{
  id: 'pub-114',
  type: 'journal',
  title: 'Gold nanoparticles promoted formation and biological properties of injectable hydrogels',
  authors: ['N. Bhingaradiya', 'A.K.S. Chandel', 'A. Biswas', 'A. Kumar', 'A. Yadav', 'P. Maiti', 'S. Jewrajka'],
  journal: 'Biomacromolecules',
  year: 2020,
  volume: '21',
  pages: '3782-3794',
  citescore: '9.2',
  impact_factor: '6.988',
  quartile: 'Q1',
  image: '/images/research/journal/biomacromolecules.jpg',
  link: 'https://doi.org/10.1021/acs.biomac.0c00889',
  publisher: 'American Chemical Society',
  featured: false
},
{
  id: 'pub-115',
  type: 'journal',
  title: 'A novel fixed-grid interface-tracking algorithm for rapid solidification of supercooled liquid metal',
  authors: ['V. Patel', 'A. Yadav', 'S. Sahoo', 'D. Thatoi', 'J. Winczek'],
  journal: 'Numerical Heat Transfer, Part A: Applications',
  year: 2020,
  volume: '78',
  pages: '306-320',
  citescore: '',
  impact_factor: '3.5',
  quartile: 'Q2',
  image: '/images/research/journal/numerical_heat_transfer.jpg',
  link: 'https://doi.org/10.1080/10407782.2020.1791542',
  publisher: 'Taylor & Francis',
  featured: false
},
{
  id: 'pub-116',
  type: 'journal',
  title: 'Electron beam processing of sensors relevant Vacoflux-49 alloy: Experimental studies of thermal zones and microstructure',
  authors: ['P. Kumar', 'A. Yadav', 'A. Kumar'],
  journal: 'Archives of Metallurgy and Materials',
  year: 2020,
  volume: '65',
  pages: '1147-1156',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/archives_of_metallurgy.jpg',
  link: 'https://doi.org/10.24425/amm.2020.133232',
  publisher: 'Polish Academy of Sciences / Institute of Metallurgy and Materials Science',
  featured: false
},
{
  id: 'pub-117',
  type: 'journal',
  title: 'Optimization of process parameters during WEDM of EN-42 spring steel',
  authors: ['L. Prasad', 'M. Upreti', 'A. Yadav', 'R.V. Patel', 'V. Kumar', 'A. Kumar'],
  journal: 'SN Applied Sciences',
  year: 2020,
  volume: '2',
  pages: '947',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/sn_applied_sciences.jpg',
  link: 'https://doi.org/10.1007/s42452-020-2650-2',
  publisher: 'Springer Nature',
  featured: false
},


    {
  id: 'pub-118',
  type: 'journal',
  title: 'Properties of functionally gradient composites reinforced with waste natural fillers',
  authors: ['L. Prasad', 'G. Singh', 'A. Yadav', 'V. Kumar', 'A. Kumar'],
  journal: 'Acta Periodica Technologica',
  year: 2019,
  volume: '50',
  pages: '250-259',
  citescore: '',
  impact_factor: '',
  quartile: '',
  image: '/images/research/journal/acta_periodica_technologica.jpg',
  link: 'https://doi.org/10.2298/APT1950250P',
  publisher: 'University of Novi Sad, Faculty of Technology',
  featured: false
},
{
  id: 'pub-119',
  type: 'journal',
  title: 'Heat transfer augmentation in automobile radiator using Al₂O₃–water based nanofluid',
  authors: ['P. Chaurasia', 'A. Kumar', 'A. Yadav', 'P.K. Kumar', 'V. Kumar', 'L. Prasad'],
  journal: 'SN Applied Sciences',
  year: 2019,
  volume: '1',
  pages: '257',
  citescore: '2.4',
  impact_factor: '',
  quartile: 'Q3',
  image: '/images/research/journal/sn_applied_sciences.jpg',
  link: 'https://doi.org/10.1007/s42452-019-0260-7',
  publisher: 'Springer Nature',
  featured: false
},
{
  id: 'pub-120',
  type: 'journal',
  title: 'Numerical study of temperature distributions and solidification pattern in the weld pool of arc welded plate',
  authors: ['A. Yadav', 'A. Kumar', 'P. Gupta', 'D.K. Sinha'],
  journal: 'Defect and Diffusion Forum',
  year: 2019,
  volume: '392',
  pages: '218-227',
  citescore: '0.9',
  impact_factor: '',
  quartile: 'Q4',
  image: '/images/research/journal/defect_diffusion_forum.jpg',
  link: 'https://doi.org/10.4028/www.scientific.net/DDF.392.218',
  publisher: 'Trans Tech Publications',
  featured: false
},
{
  id: 'pub-121',
  type: 'journal',
  title: 'Experimental and numerical study of thermal field and weld bead characteristics in submerged arc welded plate',
  authors: ['A. Yadav', 'A. Ghosh', 'A. Kumar'],
  journal: 'Journal of Materials Processing Technology',
  year: 2017,
  volume: '248',
  pages: '262-274',
  citescore: '13.6',
  impact_factor: '6.2',
  quartile: 'Q1',
  image: '/images/research/journal/j_mat_protec.jpg',
  link: 'https://doi.org/10.1016/j.jmatprotec.2017.05.021',
  publisher: 'Elsevier',
  featured: false
},
{
  id: 'pub-122',
  type: 'journal',
  title: 'Modelling and experimental validation of moving tilted volumetric heat source in gas metal arc welding process',
  authors: ['A. Ghosh', 'A. Yadav', 'A. Kumar'],
  journal: 'Journal of Materials Processing Technology',
  year: 2017,
  volume: '239',
  pages: '52-65',
  citescore: '13.6',
  impact_factor: '6.2',
  quartile: 'Q1',
  image: '/images/research/journal/j_mat_protec.jpg',
  link: 'https://doi.org/10.1016/j.jmatprotec.2016.08.010',
  publisher: 'Elsevier',
  featured: false
},


],
  conferences: [
    {
    id: 'conf-01',
    type: 'conference',
    title: null,
    authors: null,
    conference: null,
    year: null,
    location: null,
    publisher: null,
    featured: false
  }
  ],
 books: [
   
//{
//  id: 'book-07',
//  title: 'Archaeopedia',
 // authors: ['H. Pathak', 'A.Yadav'],
//  image: '/images/research/books/book7.png',
//  publisher: 'Tata McGraw-Hill',
//  year: 2026,
//  link: '',
//  isbn: '',
//  eisbn: '',
//  doi: '',
//  featured: false
//},

{
  id: 'book-06',
  title: 'Boron nitride nanomaterials-based adsorbents for water treatment',
  authors: ['A.Yadav','N. Sinha'],
  image: '/images/research/books/book6.png',
  publisher: 'International Water Association Publishing (Proposal submitted)',
  year: 2026,
  link: '',
  isbn: '',
  eisbn: '',
  doi: '',
  featured: false
},
   
{
  id: 'book-05',
  title: 'Integrated Water Architecture and Urban Infrastructure in the Sapta Puris of India',
  authors: ['H. Pathak', 'A.Yadav'],
  image: '/images/research/books/book5.png',
  publisher: 'Apple Academic Publishers, CRC Press (Proposal submitted)',
  year: 2026,
  link: '',
  isbn: '',
  eisbn: '',
  doi: '',
  featured: false
},
   
{
  id: 'book-04',
  title: 'Computational techniques for simulating and optimizing membrane processes for (waste)water treatment',
  authors: ['A.Yadav', 'R.V. Patel', 'P.K. Labhasetwar'],
  image: '/images/research/books/book4.png',
  publisher: 'International Water Association Publishing (Proposal submitted)',
  year: 2026,
  link: '',
  isbn: '',
  eisbn: '',
  doi: '',
  featured: false
},
   
{ 
  id: 'book-03',
   title: 'Applications of two-dimensional nanomaterials for water and wastewater treatment',
   authors: ['A.Yadav', 'R. Yadav', 'P.K. Labhasetwar'],
   image: '/images/research/books/book3.jpg',
   publisher: 'Apple Academic Publishers, CRC Press',
  year: 2026,
  link: 'https://www.appleacademicpress.com/applications-of-two-dimensional-nanomaterials-in-water-and-wastewater-treatment-/9781779642967',
  isbn: '9781779642967',
  eisbn: '9781779642974',
  doi: '',
  featured: true 
},
   
{
  id: 'book-02',
  title: 'Computational techniques for simulating and optimizing adsorption processes for (waste)water treatment',
  authors: ['A.Yadav', 'P.K. Labhasetwar'],
  image: '/images/research/books/book2.png',
  publisher: 'International Water Association Publishing',
  year: 2025,
  link: '',
  isbn: '',
  eisbn: '',
  doi: 'https://doi.org/10.2166/9781789063943',
  featured: false
},

{
    id: 'book-01',
    title: 'Membrane-based point-of-use drinking water treatment systems',
    authors: ['P.K. Labhasetwar', 'A.Yadav'],
    image: '/images/research/books/book1.jpeg',
    publisher: 'International Water Association Publishing',
    year: 2023,
    link: 'https://iwaponline.com/ebooks/book/867/Membrane-Based-Point-of-Use-Drinking-Water',
    isbn: '9781789062717',
    eisbn: '9781789062724',
    doi: 'https://doi.org/10.2166/9781789062724',
    featured: true
},
]
};

export const patents = [
// {
//  id: 'pat-08',
//  title: 'Dual-Channel Flow Electrodes Configuration for Simultaneous Desalination and Electrode Regeneration',
//  inventors: ['A. Yadav', 'S.S. Sahu', 'H. Pathak'],
//  patentNumber: 'IN2025110XXXXX',
//  filingDate: '31–10–2025',
//  status: 'Under preparation',
//  link: 'https://ipindia.gov.in/patent-details'
 // },
  
//  {
//  id: 'pat-07',
//  title: 'An energy-efficient multi-stage modular membrane–crystallization system for zero liquid discharge in desalination and wastewater treatment',
//  inventors: ['A. Yadav', 'A.K. Jha', 'H. Pathak', 'V. Kumar'],
 // patentNumber: 'IN2025110XXXXX',
//  filingDate: '31–10–2025',
// status: 'Under preparation',
//  link: 'https://ipindia.gov.in/patent-details'
//  },

  {
  id: 'pat-07',
  title: 'A device for iron removal and method thereof',
  inventors: ['A. Yadav', 'V. Bhoyar', 'P. Bhoyar', 'P.K. Labhasetwar', 'S.S. Sahu', 'S. Umathe', 'V. Kumar'],
  patentNumber: 'IN202511080XXX',
  filingDate: '15–11–2025',
  status: 'Under preparation',
  link: 'https://ipindia.gov.in/patent-details'
  },
  
  {
  id: 'pat-06',
  title: 'Non-electric inline chlorination device for water disinfection and method thereof',
  inventors: ['A. Yadav', 'V. Bhoyar', 'P. Bhoyar', 'P.K. Labhasetwar', 'S.S. Sahu', 'H. Pathak', 'S. Umathe', 'A. Gajbhiye', 'P. James'],
  patentNumber: 'IN202511080XXX',
  filingDate: '15–10–2025',
  status: 'Under preparation',
  link: 'https://ipindia.gov.in/patent-details'
  },
  
  {
    id: 'pat-05',
    title: 'System for predicting unmeasured water quality parameters using partial physical sensing and machine learning and method thereof',
    inventors: ['A.Yadav', 'E. Padhi', 'Y. Aragonda'],
    patentNumber: 'IN202511080121',
    filingDate: '30–09–2025',
    status: 'Under preparation',
    link: 'https://ipindia.gov.in/patent-details'
  },
  
  {
    id: 'pat-04',
    title: 'A multi-pass helical submerged membrane distillation module for desalination wastewater treating and method thereof',
    inventors: ['A.Yadav', 'B. Krishna', 'Nikhil', 'P.K. Labhasetwar'],
    patentNumber: 'IN202511089125',
    filingDate: '18–09–2025',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-03',
    title: 'Membrane distillation device integrated with fluid flow spacers for treating wastewater and method thereof',
    inventors: ['A.Yadav', 'A. Kumar', 'C.P. Singh', 'R.V. Patel'],
    patentNumber: 'IN202511070380',
    filingDate: '24–07–2025',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-02',
    title: 'A self-cleaning solar enabled smart device for real time surface water health monitoring',
    inventors: ['A.Yadav', 'E. Padhi', 'B. Krishna', 'Nikhil'],
    patentNumber: 'IN202511026994',
    filingDate: '24–03–2025',
    status: 'Published',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-01',
    title: 'Multi-pass concentric tubular module for membrane distillation',
    inventors: ['A.Yadav', 'R.V.P. Patel', 'B.M. Baladaniya', 'V.K. Shahi', 'P.K. Labhasetwar'],
    patentNumber: 'IN202411067163',
    filingDate: '05–09–2024',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
];

export const invitedTalks = [
  {
    id: 'talk-01',
    title: 'Optimizing Fouling Resistant Membranes for High Flux Distillation',
    event: '2nd International Online Conference on Sustainable Technologies in Water Treatment and Desalination',
    speaker: 'Dr. A. Yadav',
    images:['/images/research/invited_talk/IT1(1).JPG','/images/research/invited_talk/IT1(2).JPG','/images/research/invited_talk/IT1(3).JPG','/images/research/invited_talk/IT1(4).JPG','/images/research/invited_talk/IT1(5).JPG'],
    date: 2022,
    mode:'Offline',
    location: 'Location of place',
    abstract: 'Presented recent developments in optimizing membranes to reduce fouling and enhance distillation flux.'
  },
  {
    id: 'talk-02',
    title: 'Fabrication of Fouling Resistant Membranes for High Flux Distillation',
    event: 'Technical Talk at Siksha \'O\' Anusandhan University',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Siksha \'O\' Anusandhan University, Odisha',
    abstract: 'Explored fabrication methods for advanced membranes used in distillation systems.'
  },
  {
    id: 'talk-03',
    title: 'Computational Fluid Dynamics for Engineering Applications',
    event: 'Guest Lecture at Raja Ram Institute of Management and Technology',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Raja Ram Institute of Management and Technology, Lucknow',
    abstract: 'Introduced applications of computational fluid dynamics in solving complex engineering problems, especially in water treatment.'
  },
  {
    id: 'talk-04',
    title: 'Membrane Distillation for High Saline Water and Wastewater Treatment: Recent Trends and Applications',
    event: 'Technical Seminar at Harcourt Butler Technical University',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'Harcourt Butler Technical University, Kanpur',
    abstract: 'Discussed current trends and implementation strategies for membrane distillation in saline water treatment.'
  },
  {
    id: 'talk-05',
    title: 'Membrane Distillation Process for High Saline Water and Wastewater Treatment',
    event: 'Faculty Development Program on Green Energy Technology and Waste Management',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'Jayaram Institute of Technology, Nagaur',
    abstract: 'Focused on practical applications of membrane distillation in green energy and waste reduction contexts.'
  },
  {
    id: 'talk-06',
    title: 'Membrane Distillation for High Saline Water and Wastewater Treatment: Recent Trends and Applications',
    event: 'International Conference on Recent Advances in Science, Technology, Humanities and Management',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'International Conference on Recent Advances in Science, Technology, Humanities and Management (ICRASTHM)',
    abstract: 'Delivered insights on evolving techniques in saline and wastewater distillation technologies.'
  },
  {
    id: 'talk-07',
    title: 'Optimization of Fouling Resistant Membranes for High Flux',
    event: 'International Conference on Membranes and Water',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'International Conference on Membranes and Water (ICMW 2023)',
    abstract: 'Explained the optimization techniques for high-performance anti-fouling membranes.'
  },
  {
    id: 'talk-08',
    title: 'Computational Fluid Dynamics and Molecular Modelling for Engineering Applications',
    event: 'Guest Lecture at Raja Ram Institute of Management and Technology',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Raja Ram Institute of Management and Technology, Lucknow',
    abstract: 'Demonstrated use of computational fluid dynamics and molecular modeling in environmental and water engineering applications.'
  }
];
